# Generated by Django 5.1.1 on 2024-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=150)),
                ('tempo', models.TextField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
