# Generated by Django 5.1.1 on 2024-09-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_da_memoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='foto',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='tempo',
            field=models.CharField(max_length=150),
        ),
    ]
