# Generated by Django 5.1.1 on 2024-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_da_memoria', '0002_remove_jogo_foto_alter_jogo_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
