# Generated by Django 5.1.1 on 2024-12-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo_da_memoria', '0004_alter_jogo_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
